export enum FormControlNames {
  PASSWORD = 'PASSWORD',
  EMAIL = 'EMAIL',
  PASSWORD_CONFIRMATION = "PASSWORD_CONFIRMATION",
  FILTER = 'FILTER',
  PAGE = 'PAGE_INDEX',
  USERNAME = 'USERNAME',
  NAME = "NAME",
  ROLE = "ROLE",
}
